[package]
name = "min_mq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.2"
chrono = "*"
mq_message_base = { path = "../mq_message_base" }
flatbuffers = "2.0.0"
crossbeam = "0.8"